name: Update Bluesky Data

on:
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4 # Updated to the latest version

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4 # Latest version is compatible with Node.js 20
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install requests

    # Step 4: Run the Python script
    - name: Run Python script
      run: python update_bsky_data.py

    # Step 5: Commit and push changes
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.em
